### PR TITLE
Leafs fixes and things

### LINKED ISSUE #39: tardis.SetFlight(1) spams flight every tick
If you use tardis.SetFlight(1) in the lua terminal it will start flight every tick.

If you remove the demat circuit it will keep trying and even if you remove the computer the spamming doesn't stop.

### LINKED ISSUE #41: tardis.setSpeed(0) does not stop flight
When using the command tardis.setSpeed(0) the throttle just gets back to the stopped position and the tardis keeps flying without consuming energy.

using version 1.16.5-1.0.0

### PR DESCRIPTION
**Pull request by leafreynolds**
Make delayed tasks not tick forever. Flip handbrake get/set so that true = handbrake on. Time left in flight calculate correctly. Getter for destination dimension. Get dimension also returns dimension name.

### CODE REVIEW

File: src/main/java/com/vandendaelen/handles/functions/handles/GetCurrentDimension.java [hunk 1]
```diff
@@ -20,6 +22,7 @@ public boolean impactMoodAndLoyalty() {
 
     @Override
     public MethodResult run(ConsoleTile tardis, IArguments args) {
-        return MethodResult.of(DimensionHelper.getDimensionId(tardis.getCurrentDimension()));
+        final RegistryKey<World> currentDimension = tardis.getCurrentDimension();
+        return MethodResult.of(DimensionHelper.getDimensionId(tardis.getCurrentDimension()), currentDimension.location().getPath());
```
Comment (LotuxPunk) [inline src/main/java/com/vandendaelen/handles/functions/handles/GetCurrentDimension.java]: `currentDimension` can be use instead of calling the method again, no ?

Comment (LotuxPunk) [inline src/main/java/com/vandendaelen/handles/functions/handles/GetCurrentDimension.java]: What's path ?

**Review by LotuxPunk — CHANGES_REQUESTED** [review]
I'm a bit picky here ! But if you could change that I can merge without any more change, thanks again !

File: src/main/java/com/vandendaelen/handles/functions/handles/GetCurrentDimension.java (hunk 1 above)
Comment (leafreynolds) [reply src/main/java/com/vandendaelen/handles/functions/handles/GetCurrentDimension.java]: Oops! quite right, I'll fix that :)

Comment (leafreynolds) [reply src/main/java/com/vandendaelen/handles/functions/handles/GetCurrentDimension.java]: Path would be "the_nether" or "overworld", so that it doesn't show "minecraft:" in front of it. Though I'm now thinking that excluding the modid may not be the correct idea

Comment (LotuxPunk) [reply src/main/java/com/vandendaelen/handles/functions/handles/GetCurrentDimension.java]: Oh ok ! Thanks !
